CREATE TABLE category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE,
  slug VARCHAR(64) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE,
  slug VARCHAR(64) NOT NULL UNIQUE,
  color VARCHAR(32) NOT NULL DEFAULT '#e69144',
  description VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE post (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  summary VARCHAR(500) NOT NULL,
  content_markdown MEDIUMTEXT NOT NULL,
  cover_url VARCHAR(300) NULL,
  category_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE post_tag (
  post_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  PRIMARY KEY (post_id, tag_id),
  CONSTRAINT fk_post_tag_post FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_tag_tag FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE CASCADE
);

CREATE TABLE project (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(500) NOT NULL,
  tech_stack VARCHAR(300) NOT NULL,
  github_url VARCHAR(300) NULL,
  demo_url VARCHAR(300) NULL,
  sort_no INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE site_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  avatar_text VARCHAR(32) NOT NULL DEFAULT '',
  site_name VARCHAR(120) NOT NULL DEFAULT '',
  name VARCHAR(64) NOT NULL DEFAULT '',
  bio VARCHAR(500) NOT NULL DEFAULT '',
  birthday DATE NULL,
  github VARCHAR(300) NOT NULL DEFAULT '',
  email VARCHAR(120) NOT NULL DEFAULT '',
  location VARCHAR(120) NOT NULL DEFAULT '',
  show_avatar TINYINT(1) NOT NULL DEFAULT 1,
  show_name TINYINT(1) NOT NULL DEFAULT 1,
  show_bio TINYINT(1) NOT NULL DEFAULT 1,
  show_birthday TINYINT(1) NOT NULL DEFAULT 1,
  show_github TINYINT(1) NOT NULL DEFAULT 1,
  show_email TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE site_profile_skill (
  profile_id BIGINT NOT NULL,
  sort_no INT NOT NULL,
  skill_name VARCHAR(64) NOT NULL,
  PRIMARY KEY (profile_id, sort_no),
  CONSTRAINT fk_site_profile_skill_profile FOREIGN KEY (profile_id) REFERENCES site_profile(id) ON DELETE CASCADE
);

CREATE TABLE admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_post_status_published ON post(status, published_at DESC);
CREATE INDEX idx_post_category ON post(category_id);
CREATE INDEX idx_post_tag_tag_post ON post_tag(tag_id, post_id);
CREATE INDEX idx_category_status ON category(status);
