import './styles.css';
const K='sameas-atimelogger';
const now=new Date(),pad=n=>String(n).padStart(2,'0'),uid=()=>crypto.randomUUID();
const ds=d=>new Date(d).toISOString().slice(0,10),dt=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
const md=(a,b)=>Math.max(0,Math.round((b-a)/6e4)),hm=m=>m>59?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`,tm=v=>new Date(v).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),clk=s=>`${pad(s/3600|0)}:${pad((s%3600)/60|0)}:${pad(s%60)}`;
const base={view:'today',selectedDate:ds(now),activeTaskId:'reading',runningSince:null,showManual:false,tasks:[{id:'mind',name:'脑力工作',group:true,color:'#6d8cff',icon:'🧠'},{id:'reading',parent:'mind',name:'阅读',color:'#4b82f0',icon:'📘',total:260},{id:'writing',parent:'mind',name:'写作',color:'#6a5acd',icon:'✍️',total:140},{id:'life',name:'生活',group:true,color:'#65b891',icon:'🏠'},{id:'work',parent:'life',name:'工作',color:'#52b788',icon:'💼',total:420},{id:'sport',parent:'life',name:'运动',color:'#f4a261',icon:'🏃',total:95},{id:'rest',parent:'life',name:'休息',color:'#b07cf7',icon:'🛋',total:130}],tags:[{id:'focus',name:'专注',color:'#5b8def'},{id:'deep',name:'深度',color:'#7b61ff'},{id:'health',name:'健康',color:'#f59f45'},{id:'routine',name:'例行',color:'#52b788'}],logs:[{id:uid(),taskId:'work',tagId:'focus',start:new Date(now-8*36e5).toISOString(),end:new Date(now-6.8*36e5).toISOString(),note:'原型修改'},{id:uid(),taskId:'reading',tagId:'deep',start:new Date(now-5.8*36e5).toISOString(),end:new Date(now-4.6*36e5).toISOString(),note:'阅读与笔记'},{id:uid(),taskId:'sport',tagId:'health',start:new Date(now-2.5*36e5).toISOString(),end:new Date(now-1.8*36e5).toISOString(),note:'慢跑'}],draft:{taskId:'reading',tagId:'focus',start:dt(new Date(now-30*6e4)),end:dt(new Date(now-5*6e4)),note:''},newTag:{name:'',color:'#7c8cff'}};
const clone=v=>structuredClone(v),load=()=>{try{return {...clone(base),...JSON.parse(localStorage.getItem(K)||'null')}}catch{return clone(base)}};
let s=load(); const app=document.querySelector('#app');
const save=()=>localStorage.setItem(K,JSON.stringify(s)),task=id=>s.tasks.find(x=>x.id===id)||s.tasks.find(x=>!x.group),tag=id=>s.tags.find(x=>x.id===id),runS=()=>s.runningSince?Math.max(0,((Date.now()-new Date(s.runningSince))/1000|0)):0,runM=()=>runS()/60|0;
const leaf=()=>s.tasks.filter(x=>!x.group),groups=()=>s.tasks.filter(x=>x.group),groupChildren=id=>s.tasks.filter(x=>x.parent===id),dayLogs=d=>s.logs.filter(x=>ds(x.start)===d),dayM=d=>dayLogs(d).reduce((n,x)=>n+md(+new Date(x.start),+new Date(x.end)),0),taskTotal=id=>{const t=task(id);return(t.total||0)+(id===s.activeTaskId?runM():0)};
function addLog(taskId,a,b,note='',tagId=''){const t=task(taskId),m=md(+a,+b);if(!t||m<1)return;t.total=(t.total||0)+m;s.logs.unshift({id:uid(),taskId,tagId,start:a.toISOString(),end:b.toISOString(),note});}
function toggleTimer(){if(s.runningSince){const a=new Date(s.runningSince),b=new Date();if(b>a)addLog(s.activeTaskId,a,b,'计时记录',s.draft.tagId);s.runningSince=null;}else s.runningSince=new Date().toISOString();draw();}
function addManual(){const d=s.draft,a=new Date(d.start),b=new Date(d.end);if(b<=a)return;addLog(d.taskId,a,b,d.note,d.tagId);s.draft={taskId:d.taskId,tagId:d.tagId,start:dt(new Date()),end:dt(new Date(Date.now()+18e5)),note:''};s.showManual=false;draw();}
function addTag(){const name=s.newTag.name.trim();if(!name)return;const id=`tag-${Date.now()}`;s.tags.push({id,name,color:s.newTag.color||'#7c8cff'});s.newTag={name:'',color:'#7c8cff'};s.draft.tagId=id;draw();}
function todayView(){const logs=dayLogs(s.selectedDate);return logs.length?logs.map(l=>{const t=task(l.taskId),g=tag(l.tagId),m=md(+new Date(l.start),+new Date(l.end));return `<div class='log'><span class='bar' style='background:${t.color}'></span><div><div class='row'><strong>${t.icon} ${t.name}</strong><b>${hm(m)}</b></div><small>${tm(l.start)} - ${tm(l.end)}</small>${g?`<span class='tag-chip' style='--tag:${g.color}'># ${g.name}</span>`:''}<p>${l.note||'无备注'}</p></div></div>`}).join(''):`<div class='empty'>当天还没有记录。</div>`}
function calendarView(){const d=new Date(s.selectedDate),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h='';for(let i=0;i<offset;i++)h+="<div class='cell ghost'></div>";for(let i=1;i<=last;i++){const x=ds(new Date(y,m,i)),mins=dayM(x);h+=`<button class='cell ${x===s.selectedDate?'active':''}' data-a='pick' data-day='${x}'><span>${i}</span><b>${mins?hm(mins):'—'}</b></button>`}return h;}
function statsView(){const total=leaf().reduce((n,t)=>n+(t.total||0),0)+runM();return `<div class='stats-grid'>${leaf().map(t=>{const v=taskTotal(t.id),p=total?Math.round(v/total*100):0;return `<div class='statcard'><div class='row'><strong>${t.icon} ${t.name}</strong><span>${p}%</span></div><div class='meter'><i style='width:${p}%;background:${t.color}'></i></div><small>${hm(v)}</small></div>`}).join('')}</div>`;}
function categories(){return groups().map(g=>`<div class='group'><div class='group-title'><span>${g.icon}</span><strong>${g.name}</strong></div>${groupChildren(g.id).map(t=>`<button class='cat ${t.id===s.activeTaskId?'active':''}' data-a='task' data-id='${t.id}'><span class='ic' style='background:${t.color}22;color:${t.color}'>${t.icon}</span><div><strong>${t.name}</strong><small>${hm(taskTotal(t.id))}</small></div></button>`).join('')}</div>`).join('');}
function activityManager(){return `<div class='manager-list'>${leaf().map(t=>`<div class='manage-row'><span class='ic small' style='background:${t.color}22;color:${t.color}'>${t.icon}</span><div><strong>${t.name}</strong><small>${task(t.parent)?.name||''}</small></div></div>`).join('')}</div>`}
function tagManager(){return `<div class='manager-list tags'>${s.tags.map(g=>`<div class='manage-row'><span class='swatch' style='background:${g.color}'></span><div><strong>${g.name}</strong><small># ${g.id}</small></div></div>`).join('')}</div><div class='mini-form'><input data-n='name' value='${s.newTag.name}' placeholder='新标签'><input data-n='color' type='color' value='${s.newTag.color}'><button class='primary' data-a='add-tag'>添加标签</button></div>`}
function taskOptions(){return leaf().map(t=>`<option value='${t.id}' ${t.id===s.draft.taskId?'selected':''}>${t.name}</option>`).join('')}
function tagOptions(){return s.tags.map(g=>`<option value='${g.id}' ${g.id===s.draft.tagId?'selected':''}>${g.name}</option>`).join('')}
function draw(){save();const a=task(s.activeTaskId),today=dayM(ds(new Date()))+runM();app.innerHTML=`<div class='app'><aside class='side'><div class='brand'><h1>aTimeLogger</h1><span>活动分类记录</span></div><div class='menu'><button class='menu-btn ${s.view==='today'?'on':''}' data-a='view' data-view='today'>今天</button><button class='menu-btn ${s.view==='calendar'?'on':''}' data-a='view' data-view='calendar'>日历</button><button class='menu-btn ${s.view==='stats'?'on':''}' data-a='view' data-view='stats'>统计</button></div><div class='section'><div class='section-title'>活动树</div>${categories()}</div><div class='menu stack'><button class='menu-btn section-btn'>活动管理</button></div><div class='panel sidebar-panel'>${activityManager()}</div><div class='menu stack'><button class='menu-btn section-btn'>标签管理</button></div><div class='panel sidebar-panel'>${tagManager()}</div></aside><main class='main'><header class='top'><div><div class='subtle'>aTimeLogger inspired</div><h2>按活动分类追踪时间</h2></div><div class='today-card'><span>今日总计</span><strong>${hm(today)}</strong></div></header><section class='panel timer'><div><div class='subtle'>当前活动</div><h3>${a.icon} ${a.name}</h3><p>点击开始，停止后自动写入日志。</p></div><div class='timer-box'><strong>${clk(runS())}</strong><span>${s.runningSince?'记录中':'未开始'}</span></div><div class='top-actions'><input class='datepick' data-f='selectedDate' type='date' value='${s.selectedDate}'><button class='soft' data-a='toggle-manual'>添加补录</button><button class='primary' data-a='timer'>${s.runningSince?'停止记录':'开始记录'}</button></div></section><section class='panel content'>${s.view==='today'?todayView():s.view==='calendar'?`<div class='week'>${['一','二','三','四','五','六','日'].map(x=>`<span>${x}</span>`).join('')}</div><div class='calendar'>${calendarView()}</div>`:statsView()}</section>${s.showManual?`<section class='panel manual'><div class='section-title'>补录时间</div><div class='form'><select data-d='taskId'>${taskOptions()}</select><select data-d='tagId'>${tagOptions()}</select><input data-d='start' type='datetime-local' value='${s.draft.start}'><input data-d='end' type='datetime-local' value='${s.draft.end}'><input class='span-2' data-d='note' value='${s.draft.note}' placeholder='备注'></div><div class='row'><small>预计 ${hm(md(+new Date(s.draft.start),+new Date(s.draft.end)))}</small><div class='row actions-inline'><button class='soft' data-a='toggle-manual'>取消</button><button class='primary' data-a='manual'>保存记录</button></div></div></section>`:''}</main></div>`;}
app.addEventListener('click',e=>{const x=e.target.closest('[data-a]');if(!x)return;const a=x.dataset.a;if(a==='view'){s.view=x.dataset.view;draw()}if(a==='task'){s.activeTaskId=x.dataset.id;draw()}if(a==='timer')toggleTimer();if(a==='manual')addManual();if(a==='pick'){s.selectedDate=x.dataset.day;s.view='today';draw();}if(a==='add-tag')addTag();if(a==='toggle-manual'){s.showManual=!s.showManual;draw();}});
app.addEventListener('input',e=>{const x=e.target;if(x.dataset.f){s[x.dataset.f]=x.value;draw()}if(x.dataset.d){s.draft={...s.draft,[x.dataset.d]:x.value};save();}if(x.dataset.n){s.newTag={...s.newTag,[x.dataset.n]:x.value};save();}});
setInterval(()=>s.runningSince&&draw(),1000);draw();
